services:
  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: blackbox-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - blackbox-net

networks:
  blackbox-net:
    driver: bridge